const HID='soe-bq-2026-host',A=document.getElementById('app'),L='ABCD';let lv=null,pe,c,au=null,rt;
const ranks=(sc,tt=[])=>sc.map((s,i)=>({g:i+1,s,tt:Number(tt?.[i]||0)})).sort((a,b)=>b.s-a.s||a.tt-b.tt||a.g-b.g).map((x,i)=>({...x,r:i+1}));
const moveHTML=(x,rm)=>{const m=rm?.[x.g];if(!m)return '';const d=m.from-m.to;return `<span class="rank-move ${d>0?'rank-up':d<0?'rank-down':'rank-flat'}">${d>0?'▲ '+d:d<0?'▼ '+Math.abs(d):'—'}</span>`};
const row=(x,rm)=>{const g=groupInfo(x.g);return `<tr style="border-left:10px solid ${g.color}"><td class="lb-rank">${x.r}</td><td class="lb-group"><b>${g.code}</b></td><td class="lb-leader">${g.leader}</td><td class="lb-color"><span class="lb-swatch" style="background:${g.color}"></span>${g.name}</td><td class="lb-points">${x.s}</td><td class="lb-time">${Number(x.tt||0).toFixed(3)}s</td></tr>`};
const tbl=(r,rm)=>`<table class=lb><thead><tr><th> RANK </th><th> GROUP </th><th> LEADER </th><th> COLOR </th><th> POINTS </th><th> TIME </th></tr></thead><tbody>${r.map(x=>row(x,rm)).join('')}</tbody></table>`;
A.innerHTML='<div class=c><h1>🖥 SOE Bible Quiz — Projector</h1><button class=go onclick="startP()">▶ START PROJECTOR</button><p class=small>I-click ito minsan para payagan ang tunog.</p></div>';
function startP(){document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen().catch(()=>{});A.innerHTML='<div class=c><h1>Kumokonekta sa Controller…</h1></div>';connect()}
function stopAudio(){if(au){au.pause();au.currentTime=0;au=null}}
function playSfx(n){stopAudio();try{au=new Audio('assets/audio/sfx/'+n+'.wav');au.onended=()=>{au=null};au.onerror=()=>{au=null};au.play().catch(()=>{au=null})}catch(e){au=null}}
function connect(){try{pe&&pe.destroy()}catch(e){}pe=new Peer();pe.on('open',()=>{c=pe.connect(HID,{reliable:true});c.on('open',()=>c.send({t:'proj'}));c.on('data',m=>{if(m.t==='v')draw(m.v);else if(m.t==='sfx')playSfx(m.n);else if(m.t==='audio')pl(m.n)});c.on('close',retry)});pe.on('error',retry)}
function retry(){clearTimeout(rt);rt=setTimeout(connect,2000)}
function pl(n){stopAudio();if(!n)return;au=new Audio('assets/audio/'+n+'.mp3');au.onended=()=>{au=null;c.send({t:'aend'})};au.onerror=()=>{au=null;c.send({t:'aerr'})};au.play().catch(()=>{au=null;c.send({t:'aerr'})})}
function tiles(v){return `<div class=bar>${[...Array(9)].map((_,i)=>{const g=i+1,x=groupInfo(g),on=v.cn.includes(g);return `<span class=gs style="background:${x.color};color:${x.textColor};opacity:${on?1:.28};box-shadow:${on?'0 0 24px rgba(255,255,255,.75)':'none'}"><b>${x.code}</b><small style="color:inherit">${x.leader}</small><em>${x.name}</em></span>`}).join('')}</div>`}
function draw(v){v.end=Date.now()+(v.left||0);lv=v;const R=ranks(v.sc,v.rtime),as=v.as?`<p class=st>👥 Audience: ${v.as[0]} / ${v.as[1]} ang tama</p>`:'';let h;
const bar=(v.ph==='run'||v.ph==='locked'||v.ph==='reveal')&&v.cn.length?`<div class=bar><div class=group-statuses>${v.cn.slice().sort((a,b)=>a-b).map(g=>{const a=v.ad.includes(g),r=v.ph==='reveal',x=groupInfo(g);return `<span class=gs style="background:${x.color};color:${x.textColor}"><b>${x.code}</b><span>${r?(v.ok.includes(g)?'✅':'❌'):a?'⭐':'<i class=gray>☆</i>'}</span></span>`}).join('')}</div><div class=proj-timer>${v.ph==='locked'?'<span class=time-up>TIGIL! 🔴</span>':''}<span class=proj-timer-label>Segundo:</span><span id=t class=proj-timer-value></span></div></div>`:'';
if(v.fin){
  const winner=R[0], tied=R.filter(x=>x.s===winner.s&&x.tt===winner.tt),wx=groupInfo(winner.g);
  h=`<div class=c style="background:${wx.color};color:${wx.textColor}"><h1>${v.step<9?'🥁 Final Standings':'🏆 CHAMPION'}</h1>${v.step===9?`<div class=big style="color:inherit">${tied.map(x=>x.g===winner.g?wx.code:'G'+x.g).join(' & ')}</div><p>${tied.length>1?'CO-CHAMPIONS · ':''}${winner.s} puntos · ${winner.tt.toFixed(2)}s total answer time</p>`:''}${v.step?tbl(R.slice(0,v.step),v.rm):''}</div>`;
}
else if(!v.q){const u=new URL('audience.html',location.href).href;h=`<div class=c><h1>🔥 SOE Soulwinning &amp; Evangelism Bible Quiz</h1><p>${v.cn.length}/9 groups connected · 👥 ${v.ac} audience</p>${tiles(v)}<img class=qr alt="Audience QR" width=200 height=200 src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(u)}"><p class=small>Audience: ${u}</p></div>`}
else if(v.lb){const top=(v.topAud||[]).map((x,i)=>`<div>🏅 ${i+1}. ${x.n} — ${x.sc}</div>`).join('');h=v.hide?`<div class=c><h1>🔒 Suspense Mode</h1><p>Lalabas ang final standings sa dulo.</p></div>`:`<div class=c><h1>Leaderboard</h1>${tbl(R,v.rm)}${as}<div class=st><b>Top Audience</b>${top}</div></div>`}
else h=`<div class=q><div class=meta><span>${v.n?'Question '+v.n+' / 25':'Practice'}</span></div><h1>${v.q}</h1><div class=answer-panel opts>${v.o.map((t,i)=>`<div class="o o${i}${v.c>=0&&v.c!==i?' dim':''} ${v.c===i&&v.ph==='reveal'&&(v.n?`double-right`:'')}" >${L[i]}. ${t}</div>`).join('')}</div><div class=st>${v.au?'🔊 Makinig…':v.ph==='locked'?"":v.vd&&v.ph==='reveal'?'Walang puntos sa tanong na ito':''}</div>${v.ph==='reveal'&&v.rf?`<div class=rf><b>📖 ${v.rf}</b>${v.ex}</div>`:''}</div>${bar}`;
A.innerHTML=h;tick()}
function tick(){const e=document.getElementById('t');if(e)e.textContent=lv&&lv.ph==='run'?Math.max(0,Math.ceil((lv.end-Date.now())/1000)):''}setInterval(tick,200);
